services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    image: gogogo-bot:prod
    container_name: gogogo-bot
    restart: always
    env_file:
      - ../.env
    ports:
      - "8001:8001"
    stop_grace_period: 30s
